### ISSUE TITLE
Please introduce a (configurable) timeout

### ISSUE THREAD

**Issue by Xylakant** [naftulikay/travis-pls#1]
Travis provides build infrastructure for open source for free and as a good citizen of the internet, it would be polite not to abuse the offer. I understand your use case and in general consider that fine, but there should be an upper limit for the build to actually time out with a reasonable default.

**Comment by naftulikay** [comment]
I agree, I'm starting work on adding this feature. I'm typically using Travis in this manner with a paid account, so to be a good internet citizen, it should be reasonable for free Travis CI.
