### ISSUE TITLE
Seems to be broken as of recently

### ISSUE THREAD

**Issue by slavaaaaaaaaaa** [naftulikay/travis-pls#5]
In a private build of packer that I can't share much output of, travis-pls messages are all dumped after packer's. That means that this tool no longer works. 

It did before, but as of recently it does not. I'll see if I can gather more evidence.

**Comment by naftulikay** [comment]
@smaslennikov I think that Travis CI is actually banning the script. I have also noticed that things have started failing where they shouldn't.

**Comment by slavaaaaaaaaaa** [comment]
You can test this easily by doing something like:

`$ newly-built-travispls-binary sleep 660` in the travis build. I strongly recommend you do.

**Comment by naftulikay** [comment]
I am attempting to isolate the problem via [naftulikay/travis-sleaze](https://github.com/naftulikay/travis-sleaze).

**Comment by naftulikay** [comment]
I cannot verify that it is broken, so I am closing.

**Comment by Jean1995** [comment]
Is it broken again? Maybe you could request a rerun of travis on [travis-sleaze](https://github.com/naftulikay/travis-sleaze) to check? I've been trying to use travis-pls, but received no output.

**Comment by jcelerier** [comment]
tried this project yesterday but does not seem to work - see that build: https://travis-ci.org/github/ossia/score/jobs/767409044
